name: Deploy Java Project

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    name: Deploy to Linux Server
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
          
      # Setup JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build the project using Gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      # Grant execute permission for gradlew
      - name: Grant Execute Permission for Gradlew
        run: chmod +x ssgssag/gradlew

      # Ensure build/libs directory exists and contains necessary files
      - name: List files in build/libs directory
        run: ls -la ./build/libs/
        
      - name: Build Project
        run: |
          echo "spring:" > ssgssag/src/main/resources/application-db.yml
          echo "  datasource:" >> ssgssag/src/main/resources/application-db.yml
          echo "    driver-class-name: ${{ secrets.DRIVER_CLASS_NAME }}" >> ssgssag/src/main/resources/application-db.yml
          echo "    url: ${{ secrets.URL }}" >> ssgssag/src/main/resources/application-db.yml
          echo "    username: ${{ secrets.USERNAME }}" >> ssgssag/src/main/resources/application-db.yml
          echo "    password: ${{ secrets.PASSWORD }}" >> ssgssag/src/main/resources/application-db.yml


      # Deploy to Remote Server
      - name: Deploy to Remote Server
        env:
          SERVER_HOST: ${{ secrets.EC2_HOST }}
          SERVER_USER: ${{ secrets.EC2_USERNAME }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts
          
          # SSH into the server and prepare the deployment folder
          ssh $SERVER_USER@$SERVER_HOST 'bash -s' << 'EOF'
            sudo mkdir -p /opt/ssgssag/config
            sudo chown -R $USER:$USER /opt/ssgssag
            sudo chmod -R 755 /opt/ssgssag
          EOF
          
          # Copy files to the deployment folder
          scp ./build/libs/ssgssag-0.0.1-SNAPSHOT.jar $SERVER_USER@$SERVER_HOST:/opt/ssgssag/
          scp ssgssag/src/main/resources/application-db.yml $SERVER_USER@$SERVER_HOST:/opt/ssgssag/config/
          scp ssgssag/src/main/resources/application-secret.properties $SERVER_USER@$SERVER_HOST:/opt/ssgssag/config/

          # Restart the application
          ssh $SERVER_USER@$SERVER_HOST 'bash -s' << 'EOF'
            chmod +x /opt/ssgssag/run.sh
            /opt/ssgssag/run.sh restart
          EOF
