name: SSGSSAG

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v2
    - name: Run pwd #step의 이름
      run: pwd #실제 동작 코드
    - name: Run ls -al
      run: ls -al #디렉터리에 어떤 파일이 있는가
